// Valid 5-letter words for Word Duel
// This is a subset - in production, use a full word list

export const VALID_WORDS = new Set([
  // Common words
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
  'allow', 'alone', 'along', 'alter', 'among', 'angel', 'anger', 'angle', 'angry', 'apart',
  'apple', 'apply', 'arena', 'argue', 'arise', 'armor', 'array', 'arrow', 'aside', 'asset',
  'avoid', 'award', 'aware', 'awful', 'bacon', 'badge', 'badly', 'baker', 'bases', 'basic',
  'basin', 'basis', 'batch', 'beach', 'beast', 'began', 'begin', 'being', 'below', 'bench',
  'bible', 'bikes', 'birds', 'birth', 'black', 'blade', 'blame', 'bland', 'blank', 'blast',
  'blaze', 'bleed', 'blend', 'bless', 'blind', 'blink', 'block', 'blood', 'bloom', 'blown',
  'blues', 'blunt', 'board', 'boast', 'boats', 'bonds', 'bones', 'bonus', 'books', 'boost',
  'booth', 'boots', 'bound', 'brain', 'brake', 'brand', 'brass', 'brave', 'bread', 'break',
  'breed', 'brick', 'bride', 'brief', 'bring', 'broad', 'broke', 'brook', 'brown', 'brush',
  'buddy', 'build', 'built', 'bunch', 'burst', 'buyer', 'cabin', 'cable', 'cache', 'camel',
  'camps', 'canal', 'candy', 'cards', 'cargo', 'carry', 'cases', 'catch', 'cause', 'cease',
  'chain', 'chair', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'check', 'cheek', 'cheer',
  'chess', 'chest', 'chief', 'child', 'chile', 'china', 'chips', 'chord', 'chose', 'chunk',
  'cinch', 'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk', 'click', 'cliff',
  'climb', 'cling', 'clock', 'clone', 'close', 'cloth', 'cloud', 'clubs', 'coach', 'coast',
  'could', 'count', 'court', 'cover', 'crack', 'craft', 'crane', 'crash', 'crawl', 'crazy',
  'cream', 'creek', 'crime', 'crisp', 'cross', 'crowd', 'crown', 'crude', 'cruel', 'crush',
  'cubic', 'curve', 'cycle', 'daily', 'dairy', 'dance', 'dated', 'dealt', 'death', 'debut',
  'decay', 'delay', 'delta', 'dense', 'depth', 'devil', 'diary', 'digit', 'dirty', 'disco',
  'ditch', 'diver', 'dizzy', 'doing', 'donor', 'doubt', 'dozen', 'draft', 'drain', 'drama',
  'drank', 'drawn', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive', 'drown',
  'drugs', 'drums', 'drunk', 'dusty', 'dwell', 'dying', 'eager', 'early', 'earth', 'eaten',
  'edges', 'eight', 'elder', 'elect', 'elite', 'email', 'empty', 'enemy', 'enjoy', 'enter',
  'entry', 'equal', 'equip', 'error', 'essay', 'ethic', 'event', 'every', 'exact', 'exams',
  'exist', 'extra', 'faint', 'fairy', 'faith', 'false', 'fancy', 'fatal', 'fault', 'favor',
  'feast', 'fence', 'ferry', 'fever', 'fiber', 'field', 'fifth', 'fifty', 'fight', 'final',
  'first', 'fixed', 'flame', 'flash', 'flesh', 'flies', 'float', 'flood', 'floor', 'flour',
  'fluid', 'flush', 'flyer', 'focus', 'foggy', 'force', 'forge', 'forth', 'forty', 'forum',
  'found', 'frame', 'frank', 'fraud', 'fresh', 'fried', 'front', 'frost', 'fruit', 'fully',
  'funny', 'fuzzy', 'gains', 'games', 'gamma', 'gauge', 'genre', 'ghost', 'giant', 'given',
  'gives', 'gland', 'glass', 'globe', 'glory', 'glove', 'goods', 'goose', 'grace', 'grade',
  'grain', 'grand', 'grant', 'grape', 'grasp', 'grass', 'grave', 'great', 'greed', 'greek',
  'green', 'greet', 'grief', 'grill', 'grind', 'gross', 'group', 'grove', 'grown', 'guard',
  'guess', 'guest', 'guide', 'guilt', 'habit', 'hands', 'handy', 'happy', 'harsh', 'haste',
  'haven', 'heads', 'heard', 'heart', 'heavy', 'hedge', 'heels', 'hello', 'hence', 'herbs',
  'hills', 'hints', 'hobby', 'holds', 'holes', 'honey', 'honor', 'hoped', 'horse', 'hosts',
  'hotel', 'hours', 'house', 'human', 'humor', 'hurry', 'hydro', 'ideal', 'ideas', 'image',
  'imply', 'index', 'indie', 'inner', 'input', 'intel', 'inter', 'intro', 'issue', 'items',
  'ivory', 'jeans', 'jelly', 'jewel', 'joker', 'joint', 'jolly', 'judge', 'juice', 'jumbo',
  'keeps', 'kicks', 'kinds', 'kings', 'knees', 'knife', 'knock', 'known', 'label', 'labor',
  'lacks', 'lakes', 'lamps', 'lands', 'lanes', 'large', 'laser', 'later', 'laugh', 'layer',
  'leads', 'learn', 'lease', 'least', 'leave', 'legal', 'lemon', 'level', 'lever', 'light',
  'limit', 'liner', 'lines', 'links', 'lions', 'lists', 'liver', 'lives', 'loans', 'lobby',
  'local', 'locks', 'lodge', 'logic', 'logos', 'looks', 'loose', 'lords', 'lorry', 'loser',
  'lossy', 'lotus', 'lover', 'lower', 'loyal', 'lucky', 'lunch', 'lunar', 'lying', 'lyric',
  'magic', 'major', 'maker', 'males', 'manga', 'manor', 'maple', 'march', 'marks', 'marsh',
  'match', 'mates', 'maybe', 'mayor', 'meals', 'means', 'meant', 'medal', 'media', 'melon',
  'mercy', 'merge', 'merit', 'merry', 'messy', 'metal', 'meter', 'micro', 'midst', 'might',
  'miles', 'minds', 'mines', 'minor', 'minus', 'mixed', 'model', 'modem', 'modes', 'moist',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie', 'muddy',
  'multi', 'mummy', 'music', 'naive', 'naked', 'named', 'names', 'nasty', 'naval', 'needs',
  'nerve', 'never', 'newer', 'newly', 'nexus', 'night', 'ninja', 'ninth', 'noble', 'noise',
  'north', 'notch', 'noted', 'notes', 'novel', 'nurse', 'nylon', 'occur', 'ocean', 'offer',
  'often', 'olive', 'onion', 'opens', 'opera', 'orbit', 'order', 'organ', 'other', 'ought',
  'ounce', 'outer', 'owned', 'owner', 'oxide', 'ozone', 'packs', 'pages', 'paint', 'pairs',
  'panic', 'pants', 'paper', 'parks', 'party', 'pasta', 'paste', 'patch', 'paths', 'pause',
  'peace', 'peach', 'pearl', 'penny', 'perks', 'petty', 'phase', 'phone', 'photo', 'piano',
  'picks', 'piece', 'pills', 'pilot', 'pinch', 'pipes', 'pitch', 'pixel', 'pizza', 'place',
  'plain', 'plane', 'plant', 'plate', 'plaza', 'plead', 'plots', 'plugs', 'poems', 'poets',
  'point', 'poker', 'polar', 'polls', 'pools', 'porch', 'ports', 'posed', 'posts', 'pound',
  'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'privy', 'prize', 'probe',
  'promo', 'prone', 'proof', 'prose', 'proud', 'prove', 'proxy', 'pulse', 'pumps', 'punch',
  'pupil', 'puppy', 'purse', 'queen', 'query', 'quest', 'queue', 'quick', 'quiet', 'quilt',
  'quota', 'quote', 'radar', 'radio', 'rails', 'raise', 'rally', 'ranch', 'range', 'ranks',
  'rapid', 'rated', 'rates', 'ratio', 'reach', 'react', 'reads', 'ready', 'realm', 'rebel',
  'refer', 'reign', 'relax', 'relay', 'remix', 'renew', 'reply', 'reset', 'resin', 'rider',
  'ridge', 'rifle', 'right', 'rigid', 'rigor', 'rings', 'risen', 'risks', 'risky', 'rival',
  'river', 'roads', 'robot', 'rocks', 'rocky', 'roman', 'rooms', 'roots', 'roses', 'rough',
  'round', 'route', 'royal', 'rugby', 'ruled', 'ruler', 'rules', 'rumor', 'rural', 'rusty',
  'sadly', 'safer', 'saint', 'salad', 'sales', 'salon', 'sandy', 'sauce', 'saved', 'scale',
  'scare', 'scarf', 'scene', 'scent', 'scope', 'score', 'scout', 'scrap', 'seals', 'seats',
  'seeks', 'seems', 'seize', 'sells', 'sends', 'sense', 'setup', 'seven', 'shade', 'shaft',
  'shake', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheep', 'sheer', 'sheet',
  'shelf', 'shell', 'shift', 'shine', 'shiny', 'ships', 'shirt', 'shock', 'shoes', 'shook',
  'shoot', 'shops', 'shore', 'short', 'shots', 'shown', 'shows', 'sides', 'sight', 'sigma',
  'signs', 'silly', 'since', 'sites', 'sixth', 'sixty', 'sized', 'sizes', 'skill', 'skirt',
  'skull', 'slave', 'sleek', 'sleep', 'slice', 'slide', 'slope', 'slots', 'small', 'smart',
  'smell', 'smile', 'smith', 'smoke', 'snake', 'snowy', 'socks', 'soils', 'solar', 'solid',
  'solve', 'songs', 'sonic', 'sorry', 'sorts', 'souls', 'sound', 'south', 'space', 'spare',
  'spark', 'speak', 'spear', 'specs', 'speed', 'spell', 'spend', 'spent', 'spice', 'spicy',
  'spine', 'spite', 'split', 'spoke', 'spoon', 'sport', 'spots', 'spray', 'squad', 'stack',
  'staff', 'stage', 'stain', 'stake', 'stamp', 'stand', 'stark', 'stars', 'start', 'state',
  'stays', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer', 'stems', 'steps', 'stick',
  'stiff', 'still', 'stock', 'stole', 'stone', 'stood', 'stool', 'stops', 'store', 'storm',
  'story', 'stove', 'strap', 'straw', 'strip', 'stuck', 'study', 'stuff', 'style', 'sugar',
  'suite', 'sunny', 'super', 'surge', 'sushi', 'swamp', 'swear', 'sweat', 'sweep', 'sweet',
  'swept', 'swift', 'swing', 'swiss', 'sword', 'table', 'tacky', 'takes', 'tales', 'talks',
  'tanks', 'taste', 'tasty', 'taxes', 'teach', 'teams', 'tears', 'teens', 'teeth', 'tells',
  'tempo', 'tends', 'tenor', 'tense', 'tenth', 'terms', 'tests', 'texas', 'texts', 'thank',
  'theft', 'theme', 'thick', 'thief', 'thigh', 'thing', 'think', 'third', 'those', 'three',
  'threw', 'throw', 'thumb', 'tiger', 'tight', 'tiles', 'times', 'tiny',  'tired', 'title',
  'toast', 'today', 'token', 'tones', 'tools', 'tooth', 'topic', 'torch', 'total', 'touch',
  'tough', 'tours', 'towel', 'tower', 'towns', 'toxic', 'trace', 'track', 'trade', 'trail',
  'train', 'trait', 'trash', 'treat', 'trees', 'trend', 'trial', 'tribe', 'trick', 'tried',
  'tries', 'trips', 'troop', 'truck', 'truly', 'trunk', 'trust', 'truth', 'tubes', 'tumor',
  'tunes', 'turbo', 'turns', 'tutor', 'tweet', 'twice', 'twins', 'twist', 'typed', 'types',
  'ultra', 'uncle', 'under', 'undue', 'unfair','union', 'unite', 'units', 'unity', 'until',
  'upper', 'upset', 'urban', 'urged', 'usage', 'users', 'using', 'usual', 'utter', 'vague',
  'valid', 'value', 'valve', 'vapor', 'vault', 'vegas', 'venue', 'verge', 'verse', 'video',
  'views', 'villa', 'vinyl', 'viral', 'virus', 'visit', 'vista', 'vital', 'vivid', 'vocal',
  'vodka', 'vogue', 'voice', 'voted', 'voter', 'votes', 'wages', 'wagon', 'waist', 'walks',
  'walls', 'wants', 'waste', 'watch', 'water', 'watts', 'waves', 'wears', 'wedge', 'weeds',
  'weeks', 'weigh', 'weird', 'wells', 'whale', 'wheat', 'wheel', 'where', 'which', 'while',
  'white', 'whole', 'whose', 'wider', 'width', 'winds', 'wines', 'wings', 'wired', 'wires',
  'witch', 'wives', 'woman', 'women', 'woods', 'words', 'works', 'world', 'worms', 'worry',
  'worse', 'worst', 'worth', 'would', 'wound', 'woven', 'wraps', 'wrath', 'wreck', 'wrist',
  'write', 'wrong', 'wrote', 'yacht', 'yards', 'years', 'yeast', 'yield', 'young', 'yours',
  'youth', 'zebra', 'zones',
]);

// Words that can be used as secret words (more common, guessable)
export const SECRET_WORDS = [
  'about', 'above', 'actor', 'admit', 'adopt', 'adult', 'after', 'again', 'agent', 'agree',
  'ahead', 'album', 'alert', 'alien', 'allow', 'alone', 'along', 'among', 'angel', 'angry',
  'apple', 'arena', 'argue', 'armor', 'arrow', 'aside', 'avoid', 'award', 'beach', 'beast',
  'begin', 'below', 'black', 'blade', 'blame', 'blank', 'blast', 'blend', 'blind', 'block',
  'blood', 'bloom', 'board', 'bonus', 'boost', 'brain', 'brake', 'brand', 'brave', 'bread',
  'break', 'brick', 'brief', 'bring', 'broad', 'brown', 'brush', 'build', 'burst', 'cabin',
  'cable', 'candy', 'carry', 'catch', 'cause', 'chain', 'chair', 'charm', 'chart', 'chase',
  'cheap', 'check', 'chess', 'chest', 'chief', 'child', 'china', 'claim', 'class', 'clean',
  'clear', 'click', 'climb', 'clock', 'clone', 'close', 'cloud', 'coach', 'coast', 'could',
  'count', 'court', 'cover', 'crack', 'craft', 'crane', 'crash', 'crazy', 'cream', 'crime',
  'cross', 'crowd', 'crown', 'crush', 'curve', 'cycle', 'daily', 'dance', 'death', 'delay',
  'depth', 'dirty', 'doubt', 'dozen', 'draft', 'drain', 'drama', 'dream', 'dress', 'drink',
  'drive', 'drums', 'early', 'earth', 'eight', 'elite', 'email', 'empty', 'enemy', 'enjoy',
  'enter', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exist', 'extra', 'faith',
  'false', 'fancy', 'fatal', 'fault', 'favor', 'feast', 'fiber', 'field', 'fifth', 'fifty',
  'fight', 'final', 'first', 'flame', 'flash', 'floor', 'flour', 'fluid', 'focus', 'force',
  'forth', 'forty', 'forum', 'found', 'frame', 'fresh', 'front', 'frost', 'fruit', 'funny',
  'games', 'ghost', 'giant', 'given', 'glass', 'globe', 'glory', 'glove', 'grace', 'grade',
  'grain', 'grand', 'grant', 'grape', 'grass', 'grave', 'great', 'green', 'greet', 'grief',
  'grill', 'gross', 'group', 'grove', 'grown', 'guard', 'guess', 'guest', 'guide', 'guilt',
  'habit', 'happy', 'harsh', 'heart', 'heavy', 'hello', 'hills', 'hobby', 'honey', 'honor',
  'horse', 'hotel', 'hours', 'house', 'human', 'humor', 'hurry', 'ideal', 'image', 'index',
  'inner', 'input', 'issue', 'items', 'jeans', 'jewel', 'joint', 'judge', 'juice', 'keeps',
  'knife', 'known', 'label', 'labor', 'large', 'laser', 'later', 'laugh', 'layer', 'learn',
  'least', 'leave', 'legal', 'lemon', 'level', 'light', 'limit', 'links', 'lions', 'lists',
  'liver', 'lives', 'local', 'logic', 'looks', 'loose', 'lover', 'lower', 'loyal', 'lucky',
  'lunch', 'lying', 'magic', 'major', 'maker', 'march', 'match', 'maybe', 'mayor', 'meals',
  'means', 'media', 'mercy', 'merit', 'merry', 'metal', 'might', 'minor', 'mixed', 'model',
  'money', 'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'moved', 'movie', 'music',
  'naked', 'named', 'names', 'naval', 'needs', 'nerve', 'never', 'night', 'ninth', 'noble',
  'noise', 'north', 'noted', 'notes', 'novel', 'nurse', 'occur', 'ocean', 'offer', 'often',
  'olive', 'onion', 'opens', 'opera', 'orbit', 'order', 'organ', 'other', 'ought', 'outer',
  'owned', 'owner', 'paint', 'panic', 'paper', 'party', 'pasta', 'patch', 'pause', 'peace',
  'pearl', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch', 'pixel', 'pizza',
  'place', 'plain', 'plane', 'plant', 'plate', 'point', 'polar', 'pools', 'pound', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'proof', 'proud', 'prove',
  'pulse', 'punch', 'queen', 'query', 'quest', 'queue', 'quick', 'quiet', 'quote', 'radar',
  'radio', 'raise', 'rally', 'ranch', 'range', 'rapid', 'reach', 'react', 'ready', 'realm',
  'rebel', 'refer', 'relax', 'reply', 'rider', 'ridge', 'rifle', 'right', 'rigid', 'rings',
  'risen', 'risks', 'rival', 'river', 'roads', 'robot', 'rocks', 'roman', 'rooms', 'roots',
  'rough', 'round', 'route', 'royal', 'rugby', 'rules', 'rumor', 'rural', 'sadly', 'safer',
  'saint', 'salad', 'sales', 'sauce', 'saved', 'scale', 'scare', 'scene', 'scent', 'scope',
  'score', 'scout', 'seats', 'seeks', 'seems', 'seize', 'sells', 'sends', 'sense', 'setup',
  'seven', 'shade', 'shake', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp', 'sheep',
  'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shiny', 'ships', 'shirt', 'shock',
  'shoes', 'shook', 'shoot', 'shops', 'shore', 'short', 'shots', 'shown', 'shows', 'sides',
  'sight', 'signs', 'silly', 'since', 'sites', 'sixth', 'sixty', 'sized', 'skill', 'skull',
  'slave', 'sleep', 'slice', 'slide', 'slope', 'small', 'smart', 'smell', 'smile', 'smoke',
  'snake', 'solid', 'solve', 'songs', 'sorry', 'sorts', 'souls', 'sound', 'south', 'space',
  'spare', 'spark', 'speak', 'speed', 'spell', 'spend', 'spent', 'spice', 'spine', 'spite',
  'split', 'spoke', 'spoon', 'sport', 'spots', 'spray', 'squad', 'stack', 'staff', 'stage',
  'stain', 'stake', 'stamp', 'stand', 'stars', 'start', 'state', 'stays', 'steak', 'steal',
  'steam', 'steel', 'steep', 'steps', 'stick', 'stiff', 'still', 'stock', 'stone', 'stood',
  'stops', 'store', 'storm', 'story', 'stove', 'strap', 'strip', 'stuck', 'study', 'stuff',
  'style', 'sugar', 'suite', 'sunny', 'super', 'surge', 'swear', 'sweat', 'sweep', 'sweet',
  'swept', 'swift', 'swing', 'sword', 'table', 'takes', 'tales', 'talks', 'tanks', 'taste',
  'teach', 'teams', 'tears', 'teens', 'teeth', 'tells', 'terms', 'tests', 'thank', 'theft',
  'theme', 'thick', 'thief', 'thing', 'think', 'third', 'those', 'three', 'threw', 'throw',
  'thumb', 'tiger', 'tight', 'times', 'tired', 'title', 'toast', 'today', 'token', 'tones',
  'tools', 'tooth', 'topic', 'torch', 'total', 'touch', 'tough', 'tours', 'towel', 'tower',
  'towns', 'toxic', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'treat',
  'trees', 'trend', 'trial', 'tribe', 'trick', 'tried', 'tries', 'trips', 'truck', 'truly',
  'trunk', 'trust', 'truth', 'tunes', 'turns', 'twice', 'twins', 'twist', 'typed', 'types',
  'ultra', 'uncle', 'under', 'union', 'unite', 'units', 'unity', 'until', 'upper', 'upset',
  'urban', 'usage', 'users', 'using', 'usual', 'valid', 'value', 'video', 'views', 'viral',
  'virus', 'visit', 'vital', 'vivid', 'vocal', 'voice', 'voted', 'voter', 'votes', 'wages',
  'waist', 'walks', 'walls', 'wants', 'waste', 'watch', 'water', 'waves', 'wears', 'weeks',
  'weigh', 'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white', 'whole',
  'whose', 'wider', 'width', 'winds', 'wings', 'witch', 'woman', 'women', 'woods', 'words',
  'works', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'write', 'wrong',
  'wrote', 'yacht', 'yards', 'years', 'yield', 'young', 'yours', 'youth', 'zones',
];

export function isValidWord(word: string): boolean {
  return VALID_WORDS.has(word.toLowerCase());
}

export function getRandomSecretWord(): string {
  return SECRET_WORDS[Math.floor(Math.random() * SECRET_WORDS.length)];
}
