/**
 * Official Word Duel 5-letter word list
 * Curated for common English words that work well for Wordle-style games
 * ~2300 words (solution-quality) + extended list for valid guesses
 */

// Solution words - common, well-known 5-letter words
export const SOLUTION_WORDS = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again',
  'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align', 'alike', 'alive',
  'allow', 'alone', 'along', 'alter', 'among', 'angel', 'anger', 'angle', 'angry', 'apart',
  'apple', 'apply', 'arena', 'argue', 'arise', 'armor', 'army', 'array', 'arrow', 'asset',
  'avoid', 'award', 'aware', 'awful', 'bacon', 'badge', 'badly', 'baker', 'basic', 'basis',
  'beach', 'beard', 'beast', 'began', 'begin', 'begun', 'being', 'belly', 'below', 'bench',
  'berry', 'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blaze', 'bleed', 'blend',
  'bless', 'blind', 'block', 'blood', 'bloom', 'blown', 'board', 'boast', 'bonus', 'booth',
  'brain', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brick', 'bride', 'brief',
  'bring', 'broad', 'broke', 'brown', 'brush', 'build', 'built', 'bunch', 'burst', 'buyer',
  'cabin', 'cable', 'calif', 'canal', 'candy', 'canon', 'cargo', 'carry', 'carve', 'catch',
  'cause', 'cease', 'chain', 'chair', 'chalk', 'champ', 'chaos', 'charm', 'chart', 'chase',
  'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chief', 'child', 'chill',
  'china', 'chips', 'chord', 'chose', 'chunk', 'civic', 'civil', 'claim', 'clash', 'class',
  'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clock', 'close', 'cloth',
  'cloud', 'coach', 'coast', 'coral', 'couch', 'cough', 'could', 'count', 'court', 'cover',
  'crack', 'craft', 'crane', 'crash', 'crazy', 'cream', 'creek', 'crisp', 'cross', 'crowd',
  'crown', 'crude', 'cruel', 'crush', 'curve', 'cycle', 'daily', 'dairy', 'dance', 'death',
  'debug', 'debut', 'decor', 'delay', 'delta', 'dense', 'depot', 'depth', 'diary', 'dirty',
  'disco', 'ditch', 'doubt', 'dough', 'dozen', 'draft', 'drain', 'drama', 'drank', 'drawn',
  'dread', 'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drive', 'drown', 'drove',
  'drunk', 'dusty', 'dwarf', 'dwell', 'eager', 'early', 'earth', 'eight', 'elder', 'elect',
  'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'equip', 'erase', 'error',
  'essay', 'ethic', 'event', 'every', 'exact', 'excel', 'exist', 'extra', 'faint', 'fairy',
  'faith', 'false', 'fancy', 'fault', 'feast', 'fence', 'fetch', 'fever', 'fiber', 'field',
  'fiery', 'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'flame', 'flash', 'flask',
  'flesh', 'flick', 'fling', 'float', 'flock', 'flood', 'floor', 'flour', 'flown', 'fluid',
  'flush', 'focal', 'focus', 'folly', 'force', 'forge', 'forth', 'forty', 'forum', 'found',
  'frame', 'frank', 'fraud', 'freak', 'fresh', 'fried', 'front', 'frost', 'froze', 'fruit',
  'fully', 'fungi', 'fuzzy', 'gauge', 'genre', 'ghost', 'giant', 'given', 'glade', 'gland',
  'glare', 'glass', 'gleam', 'glide', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'grace',
  'grade', 'grain', 'grand', 'grant', 'grape', 'grasp', 'grass', 'grave', 'great', 'greed',
  'greek', 'green', 'greet', 'grief', 'grill', 'grind', 'groan', 'groom', 'gross', 'group',
  'grove', 'growl', 'grown', 'guard', 'guess', 'guest', 'guide', 'guild', 'guilt', 'guise',
  'habit', 'handy', 'happy', 'harsh', 'haste', 'hatch', 'haunt', 'haven', 'heart', 'heavy',
  'hedge', 'hello', 'hence', 'herb', 'hinge', 'hobby', 'honey', 'honor', 'horse', 'hotel',
  'hound', 'house', 'human', 'humid', 'humor', 'hurry', 'hyper', 'ideal', 'image', 'imply',
  'inbox', 'incur', 'index', 'inner', 'input', 'irony', 'issue', 'ivory', 'japan', 'jelly',
  'jewel', 'joint', 'joker', 'jolly', 'judge', 'juice', 'juicy', 'jumbo', 'jumpy', 'junky',
  'karma', 'kayak', 'kebab', 'kiosk', 'kitty', 'knack', 'knead', 'kneel', 'knife', 'knock',
  'known', 'label', 'labor', 'lance', 'large', 'laser', 'latch', 'later', 'laugh', 'layer',
  'learn', 'lease', 'least', 'leave', 'ledge', 'legal', 'lemon', 'level', 'lever', 'light',
  'limit', 'linen', 'liner', 'liver', 'llama', 'local', 'lodge', 'lofty', 'logic', 'login',
  'loose', 'lorry', 'loser', 'lotus', 'loved', 'lover', 'lower', 'loyal', 'lucky', 'lunar',
  'lunch', 'lying', 'lyric', 'magic', 'major', 'maker', 'mambo', 'mango', 'manor', 'maple',
  'march', 'marry', 'marsh', 'match', 'maxim', 'maybe', 'mayor', 'medal', 'media', 'melee',
  'melon', 'mercy', 'merge', 'merit', 'merry', 'metal', 'meter', 'midst', 'might', 'mince',
  'minor', 'minus', 'mirth', 'moist', 'money', 'month', 'moose', 'moral', 'motel', 'motor',
  'motto', 'mould', 'mount', 'mouse', 'mouth', 'movie', 'muddy', 'mummy', 'music', 'naive',
  'naked', 'nasty', 'naval', 'nerve', 'never', 'newly', 'night', 'ninja', 'noble', 'noise',
  'nomad', 'north', 'notch', 'noted', 'novel', 'nurse', 'nylon', 'oasis', 'occur', 'ocean',
  'often', 'olive', 'onion', 'onset', 'opera', 'optic', 'orbit', 'order', 'organ', 'other',
  'ought', 'ounce', 'outer', 'outgo', 'owned', 'owner', 'oxide', 'ozone', 'paint', 'panel',
  'panic', 'paper', 'party', 'pasta', 'paste', 'patch', 'pause', 'peace', 'peach', 'pearl',
  'pedal', 'penny', 'perch', 'peril', 'perky', 'petal', 'petty', 'phase', 'phone', 'photo',
  'piano', 'piece', 'pilot', 'pinch', 'pitch', 'pivot', 'pixel', 'pizza', 'place', 'plaid',
  'plain', 'plane', 'plank', 'plant', 'plate', 'plaza', 'plead', 'pleat', 'pledge', 'pluck',
  'plumb', 'plume', 'plump', 'plunge', 'point', 'poker', 'polar', 'porch', 'posed', 'poser',
  'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior', 'prism', 'prize',
  'probe', 'prone', 'proof', 'prose', 'proud', 'prove', 'proxy', 'prune', 'psalm', 'pulse',
  'punch', 'pupil', 'puppy', 'purse', 'queen', 'query', 'quest', 'queue', 'quick', 'quiet',
  'quilt', 'quirk', 'quota', 'quote', 'radar', 'radio', 'raise', 'rally', 'ranch', 'range',
  'rapid', 'ratio', 'razor', 'reach', 'react', 'ready', 'realm', 'rebel', 'refer', 'reign',
  'relax', 'relay', 'relic', 'renew', 'repay', 'reply', 'rerun', 'reset', 'resin', 'retro',
  'rhyme', 'rider', 'ridge', 'rifle', 'right', 'rigid', 'rigor', 'rinse', 'ripen', 'risen',
  'risky', 'ritual', 'rival', 'river', 'roast', 'robot', 'rocky', 'rogue', 'roman', 'roost',
  'rough', 'round', 'route', 'rover', 'royal', 'rugby', 'ruins', 'ruler', 'rumor', 'rural',
  'rusty', 'sadly', 'saint', 'salad', 'sales', 'salon', 'sandy', 'sauce', 'sauna', 'saved',
  'saver', 'savor', 'scale', 'scalp', 'scant', 'scare', 'scarf', 'scary', 'scene', 'scent',
  'scold', 'scoop', 'scope', 'score', 'scout', 'scrap', 'seize', 'sense', 'serve', 'setup',
  'seven', 'shade', 'shaft', 'shake', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp',
  'shave', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shiny', 'shire',
  'shirt', 'shock', 'shore', 'short', 'shout', 'shown', 'shrub', 'siege', 'sight', 'sigma',
  'silly', 'since', 'siren', 'sixth', 'sixty', 'sized', 'skate', 'skill', 'skimp', 'skull',
  'slack', 'slain', 'slant', 'slash', 'slate', 'sleek', 'sleep', 'slept', 'slice', 'slide',
  'slim', 'sling', 'slope', 'slump', 'small', 'smart', 'smash', 'smell', 'smile', 'smoke',
  'snack', 'snake', 'snare', 'sneak', 'sniff', 'solar', 'solid', 'solve', 'sonic', 'sorry',
  'sound', 'south', 'space', 'spare', 'spark', 'spawn', 'speak', 'spear', 'speed', 'spell',
  'spend', 'spent', 'spice', 'spicy', 'spider', 'spike', 'spill', 'spine', 'spiral', 'split',
  'spoke', 'spoon', 'sport', 'spray', 'spree', 'squad', 'stack', 'staff', 'stage', 'stain',
  'stair', 'stake', 'stale', 'stamp', 'stand', 'stare', 'stark', 'start', 'state', 'stave',
  'stays', 'steady', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick',
  'stiff', 'still', 'sting', 'stint', 'stock', 'stomp', 'stone', 'stool', 'store', 'stork',
  'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray', 'strip', 'stuck', 'study',
  'stuff', 'stump', 'stung', 'stunk', 'style', 'sugar', 'suite', 'sunny', 'super', 'surge',
  'swamp', 'swarm', 'swear', 'sweat', 'sweep', 'sweet', 'swept', 'swift', 'swing', 'swipe',
  'swiss', 'sword', 'swore', 'sworn', 'swung', 'synth', 'table', 'tacky', 'taken', 'tally',
  'tango', 'tangy', 'taper', 'tardy', 'taste', 'tasty', 'taunt', 'teach', 'teeth', 'tempo',
  'tense', 'tenth', 'terms', 'terra', 'thank', 'theft', 'their', 'theme', 'there', 'these',
  'thick', 'thief', 'thigh', 'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw',
  'throw', 'thumb', 'tiger', 'tight', 'timer', 'timid', 'tipsy', 'tired', 'titan', 'title',
  'toast', 'today', 'token', 'toned', 'tonic', 'tooth', 'topic', 'torch', 'total', 'touch',
  'tough', 'tower', 'toxic', 'trace', 'track', 'trade', 'trail', 'train', 'trait', 'tramp',
  'trash', 'trawl', 'tread', 'treat', 'trend', 'trial', 'tribe', 'trick', 'tried', 'troop',
  'trout', 'truce', 'truck', 'truly', 'trump', 'trunk', 'trust', 'truth', 'tulip', 'tumor',
  'tuner', 'tunic', 'turbo', 'tutor', 'twang', 'tweed', 'tweet', 'twice', 'twine', 'twirl',
  'twist', 'tycoon', 'ultra', 'uncle', 'under', 'unify', 'union', 'unite', 'unity', 'until',
  'upper', 'upset', 'urban', 'usage', 'usher', 'usual', 'utter', 'vague', 'valid', 'valor',
  'value', 'valve', 'vapor', 'vault', 'venom', 'venue', 'verse', 'vigor', 'villa', 'vinyl',
  'viola', 'viper', 'viral', 'virus', 'visit', 'visor', 'vista', 'vital', 'vivid', 'vocal',
  'vodka', 'vogue', 'voice', 'voila', 'voter', 'vouch', 'vowel', 'wagon', 'waist', 'waltz',
  'waste', 'watch', 'water', 'waver', 'weary', 'weave', 'wedge', 'weigh', 'weird', 'whale',
  'wheat', 'wheel', 'where', 'which', 'while', 'whine', 'whirl', 'white', 'whole', 'whose',
  'widen', 'widow', 'width', 'wield', 'wired', 'witch', 'witty', 'woken', 'woman', 'women',
  'woods', 'woozy', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'woven',
  'wrath', 'wreck', 'wring', 'wrist', 'write', 'wrong', 'wrote', 'yacht', 'yearn', 'yeast',
  'yield', 'young', 'yours', 'youth', 'zebra', 'zesty', 'zippy', 'zonal', 'crane', 'crate',
  'slate', 'stare', 'scare', 'share', 'spare', 'glare', 'flare', 'snare', 'trace', 'grace',
  'brace', 'place', 'space', 'arose', 'arise', 'audio', 'adieu', 'ouija', 'raise', 'irate'
] as const

// Extended list - valid guesses but less common as solutions
export const EXTENDED_WORDS = [
  'aahed', 'aalii', 'abaca', 'abaci', 'aback', 'abaft', 'abamp', 'abase', 'abash', 'abate',
  'abbey', 'abbot', 'abeam', 'abele', 'abets', 'abhor', 'abide', 'abler', 'abode', 'abohm',
  'abort', 'bound', 'boxes', 'bozos', 'brace', 'brack', 'bract', 'brads', 'braes', 'brags',
  'raids', 'rails', 'rains', 'rainy', 'raise', 'rajah', 'rajas', 'raked', 'rakee', 'raker',
  'rakes', 'rakis', 'rales', 'rally', 'ralph', 'ramal', 'ramee', 'ramen', 'ramet', 'ramie',
  'weeds', 'weeks', 'weens', 'weeny', 'weeps', 'weepy', 'weest', 'weets', 'wefts', 'weigh',
  'weird', 'weirs', 'wekas', 'welch', 'welds', 'wells', 'welly', 'welsh', 'welts', 'wench',
  'wends', 'wenny', 'wests', 'wetly', 'whack', 'whale', 'whamo', 'whams', 'whang', 'whaps',
  'zooms', 'zoons', 'zoril', 'zoris', 'zowie', 'zuzim', 'zymes'
] as const

// All valid words combined
export const ALL_WORDS = [...SOLUTION_WORDS, ...EXTENDED_WORDS]

// Letter frequency in English (used for scoring)
export const LETTER_FREQUENCY: Record<string, number> = {
  'e': 12.7, 't': 9.1, 'a': 8.2, 'o': 7.5, 'i': 7.0,
  'n': 6.7, 's': 6.3, 'h': 6.1, 'r': 6.0, 'd': 4.3,
  'l': 4.0, 'c': 2.8, 'u': 2.8, 'm': 2.4, 'w': 2.4,
  'f': 2.2, 'g': 2.0, 'y': 2.0, 'p': 1.9, 'b': 1.5,
  'v': 1.0, 'k': 0.8, 'j': 0.15, 'x': 0.15, 'q': 0.1, 'z': 0.07
}

// Best starting words (high information gain)
export const OPTIMAL_STARTERS = [
  'salet', 'reast', 'crate', 'trace', 'slate',
  'crane', 'slant', 'carte', 'carle', 'trice'
]
